version: '3.1'
services:
  application:
    container_name: 'shipping-service'
    image: item-service
    ports:
      - '8083:8083'
    profiles: ['shipping-service']
    environment:
      POSTGRES_JDBC_USER: shippingdbuser
      POSTGRES_JDBC_PASS: piratepassword
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5435/shippingdb"
      SPRING_PROFILES_ACTIVE: local
