server:
  port: 8083
spring:
  application:
    name: shipping-service
  rabbitmq:
    host: localhost
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: shippingdbuser
    password: piratepassword
    url: jdbc:postgresql://localhost:5435/shippingdb
