server:
  port: 8083
spring:
  application:
    name: shipping-service
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect